bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [ 
    path('', views.index, name="index"),
]

config/urls.py
from django.contrib import admin

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls")),
]

bbs/models.py
from django.db import models

# Create your models here.
import uuid

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    #UUID、名前、コメント、投稿日
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(verbose_name="名前",max_length=20)
    comment     = models.CharField(verbose_name="コメント",max_length=200)
    post_dt     = models.DateTimeField(verbose_name="投稿日")

    def __str__(self):
        return self.comment

bbs/forms.py
#モデルのフィールド定義を継承し、フォームとする。
from .models import Topic
from django.forms import ModelForm,TextInput,Textarea


#ModelFormを継承し、Metaクラスに利用するモデルクラス名、フィールド、ウィジェット等を記述
class TopicForm(ModelForm):
    class Meta:
        model   = Topic
        widgets = { "name": TextInput(attrs={"class":"form-control","placeholder":"名前","autofocus":"",} ),
                    "comment":Textarea(attrs={"class":"form-control","placeholder":"ここにコメントを入力する","rows":"6"} ),
                    }
        fields  = [ "name","comment","post_dt" ]

bbs/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from .models import Topic

#フォームをインポート
from .forms import TopicForm

from django.utils import timezone

#Viewを継承してGET文、POST文の関数を作る
class BbsView(View):

    def reference(self):

        form        = TopicForm()
        topic_data  = Topic.objects.order_by("-post_dt")

        return form,topic_data

    def get(self, request, *args, **kwargs):

        form,topic_data     = self.reference()

        context     = { "data"  : topic_data,
                        "form"  : form }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        #フォームの値を受け取ったらバリデーションする。
        if "name" in request.POST and "comment" in request.POST:

            data    = { "name"      : request.POST["name"],
                        "comment"   : request.POST["comment"],
                        "post_dt"   : timezone.now(),
                        }
            formset = TopicForm(data)
        
            #バリデーションチェック
            if formset.is_valid():
                #DBに記録する
                formset.save()
            else:
                print("バリデーションエラー")

        form,topic_data     = self.reference()

        context     = { "data"  : topic_data,
                        "form"  : form }

        return render(request,"bbs/index.html",context)

index       = BbsView.as_view()

templates/bbs/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'bbs/css/style.css'%}">
</head>
<body>
    <header class="bg-primary">
        <a href="{% url 'bbs:index' %}"><h1 class="text-center text-white">簡易掲示板</h1></a>
    </header>

    <main class="container">
        <!--forms.pyから継承したviews.pyがcontext内に格納したformを参照している。-->
        <form action="" method="post">
            {% csrf_token %}
            <div class="my-2">{{ form.name }}</div>
            <div class="my-2">{{ form.comment }}</div>

            <input class="form-control" type="submit" value="送信">
        </form>

        <!--ここにBBSに投稿された物を全て掲載する。-->
        <div class="bbs_area">
            {% for content in data %}
            <div class="comment_area">
                <div class="comment_name">名前:{{ content.name }}</div>
                <div class="comment">{{ content.comment|linebreaksbr|urlize }}</div>
                <div class="comment_dt">投稿日:{{ content.post_dt }}</div>
            </div>
            {% endfor %}
        </div>

    </main>

</body>
</html>